### ISSUE TITLE
Installation was killed without a reason

### ISSUE THREAD

**Issue by geekkun** [TimboKZ/blitz#9]
![bl](https://cloud.githubusercontent.com/assets/375964/20389293/e47d1416-acc0-11e6-99ac-864e6631683c.PNG)

**Comment by TimboKZ** [comment]
> Based on the information you provided, that npm is crashing or killing it's sub-processes during this install but not at the same point each time the most likely cause is that your droplet is running out of available memory to complete the installation process. This is especially likely if you are running a 512MB droplet.

From a quick google search on why npm installations might get killed for no reason. How much RAM does your machine have?

**Comment by TimboKZ** [comment]
Closed since the issue is very unlikely to have been caused by Blitz.
